spring:
    profiles:
        active: development
    devtools:
        restart:
            enabled: true
            exclude: static/**,public/**
    thymeleaf.cache: false

server:
    port: 8000

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG

amazon:
    associateId: habuma-20
